apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-database-config
data:
  POSTGRES_DB: "auth_database"
  POSTGRES_USER: {{ .Values.authService.db.user | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth:5432/auth_database"
  SPRING_DATASOURCE_USERNAME: {{ .Values.authService.db.user | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-database-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.authService.db.password | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.authService.db.password | quote }}
  JWT_SECRET: {{ .Values.authService.db.jwtSecret | quote }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.apiGateway.image }}
          ports:
            - containerPort: {{ .Values.apiGateway.port }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.apiGateway.port | quote }}
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:{{ .Values.authService.port }}"
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service 
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{ .Values.authService.image }}
        ports:
        - containerPort: {{ .Values.authService.port }}
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secrets
        env:
        - name: SERVER_PORT
          value: {{ .Values.authService.port | quote }}
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}



