apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.postgres.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.size }}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-auth 
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-auth
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  selector:
    matchLabels:
      app: postgres-auth
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_USER
          value: {{ .Values.authService.db.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.authService.db.password | quote }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc